version: '3.1'

services:
    server:
        build: .
        container_name: 'server'
        command: sh -c 'python manage.py migrate && python manage.py makemigrations && python manage.py runserver ${server_HostPort}'
        volumes:
            - .:/app
        ports:
            - 8900:8900
        environment:
            - DATABASE_HOST=db
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    db:
        image: mysql:8.0
        restart: always
        container_name: 'db'
        env_file:
            - .env
        ports:
            - 3307:3306
        volumes:
            - db_data:/var/lib/mysql
            - ./CityNews.sql:/docker-entrypoint-initdb.d/CityNews.sql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
            interval: 5s
            timeout: 3s
            retries: 3

volumes:
    db_data:
        name: db_data
